
services:
  mycloud:
    image: tomaslobato/mycloud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ${ROOT:-~/mycloud}:/app/mycloud
    env_file:
      - ./bin/.env
    environment:
      - ROOT=/app/mycloud
    restart: unless-stopped