services:
  app:
    image: tomaslobato/mycloud
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5000
    volumes:
      - ~/mycloud:/app/mycloud
    environment:
      - ROOT=/app/mycloud
