services:
  mycloud:
    image: tomaslobato/mycloud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    volumes:
      - ~/mycloud:/app/mycloud
    environment:
      - ROOT=/app/mycloud
    restart: unless-stopped
