services:
  app:
    image: tomaslobato/mycloud
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5555:5000
    volumes:
      - ~/mycloud:/app/mycloud